// src/common/enums/error-code.enum.ts
/**
 * Standardized error codes for API responses
 * Used across all services for consistent error handling
 */
export enum ErrorCode {
  // Auth Errors (100-199)
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  
  // Validation Errors (200-299)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_ISBN = 'INVALID_ISBN',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
  
  // Member/User Errors (300-399)
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MEMBER_BLOCKED = 'MEMBER_BLOCKED',
  MEMBER_SUSPENDED = 'MEMBER_SUSPENDED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  
  // Book Errors (400-499)
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  BOOK_NOT_AVAILABLE = 'BOOK_NOT_AVAILABLE',
  BOOK_NOT_OWNED_BY_USER = 'BOOK_NOT_OWNED_BY_USER',
  INVALID_BOOK_CONDITION = 'INVALID_BOOK_CONDITION',
  
  // Exchange Errors (500-599)
  EXCHANGE_REQUEST_NOT_FOUND = 'EXCHANGE_REQUEST_NOT_FOUND',
  EXCHANGE_NOT_FOUND = 'EXCHANGE_NOT_FOUND',
  EXCHANGE_INVALID_STATUS = 'EXCHANGE_INVALID_STATUS',
  EXCHANGE_NOT_COMPLETED = 'EXCHANGE_NOT_COMPLETED',
  CANNOT_EXCHANGE_WITH_SELF = 'CANNOT_EXCHANGE_WITH_SELF',
  EXCHANGE_ALREADY_EXISTS = 'EXCHANGE_ALREADY_EXISTS',
  
  // Permission Errors (600-699)
  FORBIDDEN = 'FORBIDDEN',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  INSUFFICIENT_TRUST_SCORE = 'INSUFFICIENT_TRUST_SCORE',
  
  // Library Errors (700-799)
  LIBRARY_NOT_FOUND = 'LIBRARY_NOT_FOUND',
  WANTED_BOOK_NOT_FOUND = 'WANTED_BOOK_NOT_FOUND',
  WANTED_BOOK_DUPLICATE = 'WANTED_BOOK_DUPLICATE',
  
  // Messaging Errors (800-899)
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  
  // System Errors (900-999)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  OPERATION_FAILED = 'OPERATION_FAILED',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
}

/**
 * HTTP Status Code mapping for each error code
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  // Auth
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.EMAIL_NOT_VERIFIED]: 403,

  // Validation
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.INVALID_EMAIL_FORMAT]: 400,
  [ErrorCode.INVALID_ISBN]: 400,
  [ErrorCode.DUPLICATE_REQUEST]: 409,

  // Member/User
  [ErrorCode.MEMBER_NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.MEMBER_BLOCKED]: 403,
  [ErrorCode.MEMBER_SUSPENDED]: 403,
  [ErrorCode.EMAIL_ALREADY_EXISTS]: 409,

  // Book
  [ErrorCode.BOOK_NOT_FOUND]: 404,
  [ErrorCode.BOOK_NOT_AVAILABLE]: 400,
  [ErrorCode.BOOK_NOT_OWNED_BY_USER]: 403,
  [ErrorCode.INVALID_BOOK_CONDITION]: 400,

  // Exchange
  [ErrorCode.EXCHANGE_REQUEST_NOT_FOUND]: 404,
  [ErrorCode.EXCHANGE_NOT_FOUND]: 404,
  [ErrorCode.EXCHANGE_INVALID_STATUS]: 400,
  [ErrorCode.EXCHANGE_NOT_COMPLETED]: 400,
  [ErrorCode.CANNOT_EXCHANGE_WITH_SELF]: 400,
  [ErrorCode.EXCHANGE_ALREADY_EXISTS]: 409,

  // Permission
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.NOT_AUTHORIZED]: 403,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.INSUFFICIENT_TRUST_SCORE]: 403,

  // Library
  [ErrorCode.LIBRARY_NOT_FOUND]: 404,
  [ErrorCode.WANTED_BOOK_NOT_FOUND]: 404,
  [ErrorCode.WANTED_BOOK_DUPLICATE]: 409,

  // Messaging
  [ErrorCode.CONVERSATION_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_NOT_FOUND]: 404,

  // System
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.OPERATION_FAILED]: 500,
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
};
